export const ShippingFakeData = [
  {
    orderId: "#12340",
    userEmail: "john.doe@gmail.com",
    userType: "Premium",
    totalItems: 5,
    shippingInfo: "Tesla HQ Palo Alto, CA",
    deliveryTime: "05/12/2024",
    status: "Approve",
  },
  {
    orderId: "#12341",
    userEmail: "jane.smith@gmail.com",
    userType: "Regular",
    totalItems: 3,
    shippingInfo: "Blue Origin Kent, WA",
    deliveryTime: "05/12/2024",
    status: "Approve",
  },
  {
    orderId: "#12342",
    userEmail: "alice.wilson@gmail.com",
    userType: "Premium",
    totalItems: 6,
    shippingInfo: "Virgin Galactic Mojave, CA",
    deliveryTime: "05/12/2024",
    status: "Pending",
  },
  {
    orderId: "#12343",
    userEmail: "robert.brown@gmail.com",
    userType: "Regular",
    totalItems: 2,
    shippingInfo: "NASA Johnson Space Center, Houston, TX",
    deliveryTime: "05/12/2024",
    status: "Approve",
  },
  {
    orderId: "#12344",
    userEmail: "emily.jones@gmail.com",
    userType: "Premium",
    totalItems: 4,
    shippingInfo: "SpaceX Boca Chica, TX",
    deliveryTime: "05/12/2024",
    status: "Pending",
  },
  {
    orderId: "#12345",
    userEmail: "michael.taylor@gmail.com",
    userType: "Regular",
    totalItems: 7,
    shippingInfo: "Airbus Mobile, AL",
    deliveryTime: "05/12/2024",
    status: "Approve",
  },
  {
    orderId: "#12346",
    userEmail: "olivia.martin@gmail.com",
    userType: "Premium",
    totalItems: 8,
    shippingInfo: "Northrop Grumman, Dulles, VA",
    deliveryTime: "05/12/2024",
    status: "Pending",
  },
  {
    orderId: "#12347",
    userEmail: "william.hall@gmail.com",
    userType: "Regular",
    totalItems: 5,
    shippingInfo: "Boeing Everett, WA",
    deliveryTime: "05/12/2024",
    status: "Process",
  },
  {
    orderId: "#12348",
    userEmail: "sophia.lee@gmail.com",
    userType: "Premium",
    totalItems: 3,
    shippingInfo: "Rocket Lab, Long Beach, CA",
    deliveryTime: "05/12/2024",
    status: "Approve",
  },
  {
    orderId: "#12349",
    userEmail: "james.moore@gmail.com",
    userType: "Regular",
    totalItems: 6,
    shippingInfo: "JPL Pasadena, CA",
    deliveryTime: "05/12/2024",
    status: "Approve",
  },
];
